server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  version: v1
  header: X-Authorization
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: dev
  tokenSigningKey:  xm8EV6Hy5RMFK4EEACIDAwQus

